import { useState } from 'react';

type Language = 'en' | 'es' | 'hi' | 'ne';

type TranslationKey = 
  | 'appTitle' | 'appSubtitle' | 'nearbyEvents' | 'myEnrollments' | 'medicineReminders' 
  | 'chatWithGuardian' | 'profile' | 'guardians' | 'guardianPanel' | 'seniorMode' 
  | 'guardianMode' | 'upcomingEvents' | 'medicinesScheduled' | 'connectedGuardians'
  | 'adminDashboard' | 'adminDashboardDesc' | 'overview' | 'userManagement' 
  | 'eventManagement' | 'eventManagementDesc' | 'systemAlerts' | 'systemSettings' 
  | 'systemSettingsDesc' | 'totalUsers' | 'activeSeniors' | 'pendingAlerts' 
  | 'systemHealth' | 'recentUsers' | 'recentAlerts' | 'filter' | 'export' 
  | 'addUser' | 'edit' | 'view' | 'search' | 'settings' | 'name' | 'type' 
  | 'status' | 'joinDate' | 'lastActivity' | 'actions' | 'userProfile' 
  | 'manageYourInfo' | 'editProfile' | 'save' | 'yearsOld' | 'age' | 'address' 
  | 'emergencyContact' | 'medicalConditions' | 'stayConnected' | 'refresh' 
  | 'messages' | 'chatWith' | 'typeYourMessage' | 'morningYoga' | 'morningYogaDesc' 
  | 'healthCheckup' | 'healthCheckupDesc' | 'socialGathering' | 'socialGatheringDesc' 
  | 'enrollmentSuccess' | 'enrolledIn' | 'filterEvents' | 'healthWellness' 
  | 'healthcare' | 'social' | 'away' | 'enrolled' | 'enrollNow' | 'guardianAdded' 
  | 'invitationSent' | 'guardianRemoved' | 'connectionRemoved' | 'guardianConnections' 
  | 'manageGuardians' | 'addGuardian' | 'addNewGuardian' | 'fullName' | 'enterName' 
  | 'relation' | 'enterRelation' | 'phoneNumber' | 'enterPhone' | 'email' 
  | 'optional' | 'enterEmail' | 'sendInvitation' | 'cancel' | 'active' | 'pending' 
  | 'inactive' | 'guardianDashboard' | 'monitorLovedOnes' | 'notificationsOn' 
  | 'notificationsOff' | 'connectedSeniors' | 'lastSeen' | 'recentEnrollments' 
  | 'enrolledOn' | 'upcoming' | 'medicineAlerts' | 'scheduledFor' | 'taken' 
  | 'quickActions' | 'viewAllActivities' | 'setCustomAlerts' | 'error' 
  | 'fillAllFields' | 'medicineAdded' | 'addedSuccessfully' | 'medicineTaken' 
  | 'markedAsTaken' | 'medicineSkipped' | 'reminderSkipped' | 'stayHealthy' 
  | 'addMedicine' | 'addNewMedicine' | 'medicineName' | 'enterMedicineName' 
  | 'dosage' | 'enterDosage' | 'frequency' | 'selectFrequency' | 'onceDaily' 
  | 'twiceDaily' | 'threeTimes' | 'weekly' | 'time' | 'skip' | 'viewYourEvents'
  | 'confirmed' | 'cancelled' | 'viewDetails';

type Translations = {
  [key in Language]: {
    [key in TranslationKey]: string;
  };
};

export const useLanguage = () => {
  const [language, setLanguage] = useState<Language>('en');

  const translations: Translations = {
    en: {
      appTitle: "Senior Care Platform",
      appSubtitle: "Connecting Seniors and Guardians",
      nearbyEvents: "Nearby Events",
      myEnrollments: "My Enrollments",
      medicineReminders: "Medicine Reminders",
      chatWithGuardian: "Chat with Guardian",
      profile: "Profile",
      guardians: "Guardians",
      guardianPanel: "Guardian Panel",
      seniorMode: "Senior Mode",
      guardianMode: "Guardian Mode",
      upcomingEvents: "Upcoming Events",
      medicinesScheduled: "Medicines Scheduled",
      connectedGuardians: "Connected Guardians",
      adminDashboard: "Admin Dashboard",
      adminDashboardDesc: "Manage users, events, and system settings",
      overview: "Overview",
      userManagement: "User Management",
      eventManagement: "Event Management",
      eventManagementDesc: "Manage events, schedules, and registrations",
      systemAlerts: "System Alerts",
      systemSettings: "System Settings",
      systemSettingsDesc: "Configure system preferences and security settings",
      totalUsers: "Total Users",
      activeSeniors: "Active Seniors",
      pendingAlerts: "Pending Alerts",
      systemHealth: "System Health",
      recentUsers: "Recent Users",
      recentAlerts: "Recent Alerts",
      filter: "Filter",
      export: "Export",
      addUser: "Add User",
      edit: "Edit",
      view: "View",
      search: "Search",
      settings: "Settings",
      name: "Name",
      type: "Type",
      status: "Status",
      joinDate: "Join Date",
      lastActivity: "Last Activity",
      actions: "Actions",
      userProfile: "User Profile",
      manageYourInfo: "Manage your personal information",
      editProfile: "Edit Profile",
      save: "Save",
      yearsOld: "years old",
      age: "Age",
      address: "Address",
      emergencyContact: "Emergency Contact",
      medicalConditions: "Medical Conditions",
      stayConnected: "Stay connected with your family",
      refresh: "Refresh",
      messages: "Messages",
      chatWith: "Chat with",
      typeYourMessage: "Type your message to",
      morningYoga: "Morning Yoga Session",
      morningYogaDesc: "Join us for a gentle yoga session designed for seniors",
      healthCheckup: "Health Checkup Camp",
      healthCheckupDesc: "Free health screening and consultation with doctors",
      socialGathering: "Community Social Hour",
      socialGatheringDesc: "Meet and connect with other community members",
      enrollmentSuccess: "Enrollment Successful",
      enrolledIn: "You have been enrolled in",
      filterEvents: "Filter Events",
      healthWellness: "Health & Wellness",
      healthcare: "Healthcare",
      social: "Social",
      away: "away",
      enrolled: "Enrolled",
      enrollNow: "Enroll Now",
      guardianAdded: "Guardian Added",
      invitationSent: "Invitation sent successfully",
      guardianRemoved: "Guardian Removed",
      connectionRemoved: "Connection removed successfully",
      guardianConnections: "Guardian Connections",
      manageGuardians: "Manage your guardian connections",
      addGuardian: "Add Guardian",
      addNewGuardian: "Add New Guardian",
      fullName: "Full Name",
      enterName: "Enter full name",
      relation: "Relation",
      enterRelation: "Enter relation",
      phoneNumber: "Phone Number",
      enterPhone: "Enter phone number",
      email: "Email",
      optional: "optional",
      enterEmail: "Enter email address",
      sendInvitation: "Send Invitation",
      cancel: "Cancel",
      active: "Active",
      pending: "Pending",
      inactive: "Inactive",
      guardianDashboard: "Guardian Dashboard",
      monitorLovedOnes: "Monitor your loved ones' activities",
      notificationsOn: "Notifications On",
      notificationsOff: "Notifications Off",
      connectedSeniors: "Connected Seniors",
      lastSeen: "Last seen",
      recentEnrollments: "Recent Enrollments",
      enrolledOn: "Enrolled on",
      upcoming: "Upcoming",
      medicineAlerts: "Medicine Alerts",
      scheduledFor: "Scheduled for",
      taken: "Taken",
      quickActions: "Quick Actions",
      viewAllActivities: "View All Activities",
      setCustomAlerts: "Set Custom Alerts",
      error: "Error",
      fillAllFields: "Please fill in all required fields",
      medicineAdded: "Medicine Added",
      addedSuccessfully: "has been added successfully",
      medicineTaken: "Medicine Taken",
      markedAsTaken: "Medicine marked as taken",
      medicineSkipped: "Medicine Skipped",
      reminderSkipped: "Reminder has been skipped",
      stayHealthy: "Stay on top of your health",
      addMedicine: "Add Medicine",
      addNewMedicine: "Add New Medicine",
      medicineName: "Medicine Name",
      enterMedicineName: "Enter medicine name",
      dosage: "Dosage",
      enterDosage: "Enter dosage",
      frequency: "Frequency",
      selectFrequency: "Select frequency",
      onceDaily: "Once Daily",
      twiceDaily: "Twice Daily",
      threeTimes: "Three Times Daily",
      weekly: "Weekly",
      time: "Time",
      skip: "Skip",
      viewYourEvents: "View your upcoming and enrolled events",
      confirmed: "Confirmed",
      cancelled: "Cancelled",
      viewDetails: "View Details",
    },
    es: {
      appTitle: "Plataforma de Cuidado para Adultos Mayores",
      appSubtitle: "Conectando Adultos Mayores y Tutores",
      nearbyEvents: "Eventos Cercanos",
      myEnrollments: "Mis Inscripciones",
      medicineReminders: "Recordatorios de Medicamentos",
      chatWithGuardian: "Chatear con Tutor",
      profile: "Perfil",
      guardians: "Tutores",
      guardianPanel: "Panel de Tutor",
      seniorMode: "Modo Adulto Mayor",
      guardianMode: "Modo Tutor",
      upcomingEvents: "Próximos Eventos",
      medicinesScheduled: "Medicamentos Programados",
      connectedGuardians: "Tutores Conectados",
      adminDashboard: "Panel de Administrador",
      adminDashboardDesc: "Gestionar usuarios, eventos y configuración del sistema",
      overview: "Resumen",
      userManagement: "Gestión de Usuarios",
      eventManagement: "Gestión de Eventos", 
      eventManagementDesc: "Gestionar eventos, horarios y registros",
      systemAlerts: "Alertas del Sistema",
      systemSettings: "Configuración del Sistema",
      systemSettingsDesc: "Configurar preferencias del sistema y seguridad",
      totalUsers: "Total de Usuarios",
      activeSeniors: "Adultos Mayores Activos",
      pendingAlerts: "Alertas Pendientes",
      systemHealth: "Salud del Sistema",
      recentUsers: "Usuarios Recientes",
      recentAlerts: "Alertas Recientes",
      filter: "Filtrar",
      export: "Exportar",
      addUser: "Agregar Usuario",
      edit: "Editar",
      view: "Ver",
      search: "Buscar",
      settings: "Configuración",
      name: "Nombre",
      type: "Tipo",
      status: "Estado",
      joinDate: "Fecha de Registro",
      lastActivity: "Última Actividad",
      actions: "Acciones",
      userProfile: "Perfil de Usuario",
      manageYourInfo: "Gestiona tu información personal",
      editProfile: "Editar Perfil",
      save: "Guardar",
      yearsOld: "años",
      age: "Edad",
      address: "Dirección",
      emergencyContact: "Contacto de Emergencia",
      medicalConditions: "Condiciones Médicas",
      stayConnected: "Mantente conectado con tu familia",
      refresh: "Actualizar",
      messages: "Mensajes",
      chatWith: "Chatear con",
      typeYourMessage: "Escribe tu mensaje para",
      morningYoga: "Sesión de Yoga Matutina",
      morningYogaDesc: "Únete a nosotros para una sesión de yoga suave diseñada para adultos mayores",
      healthCheckup: "Campamento de Revisión de Salud",
      healthCheckupDesc: "Examen de salud gratuito y consulta con médicos",
      socialGathering: "Hora Social Comunitaria",
      socialGatheringDesc: "Conoce y conecta con otros miembros de la comunidad",
      enrollmentSuccess: "Inscripción Exitosa",
      enrolledIn: "Te has inscrito en",
      filterEvents: "Filtrar Eventos",
      healthWellness: "Salud y Bienestar",
      healthcare: "Atención Médica",
      social: "Social",
      away: "lejos",
      enrolled: "Inscrito",
      enrollNow: "Inscribirse Ahora",
      guardianAdded: "Tutor Agregado",
      invitationSent: "Invitación enviada exitosamente",
      guardianRemoved: "Tutor Eliminado",
      connectionRemoved: "Conexión eliminada exitosamente",
      guardianConnections: "Conexiones de Tutores",
      manageGuardians: "Gestiona tus conexiones de tutores",
      addGuardian: "Agregar Tutor",
      addNewGuardian: "Agregar Nuevo Tutor",
      fullName: "Nombre Completo",
      enterName: "Ingresa nombre completo",
      relation: "Relación",
      enterRelation: "Ingresa relación",
      phoneNumber: "Número de Teléfono",
      enterPhone: "Ingresa número de teléfono",
      email: "Correo Electrónico",
      optional: "opcional",
      enterEmail: "Ingresa dirección de correo",
      sendInvitation: "Enviar Invitación",
      cancel: "Cancelar",
      active: "Activo",
      pending: "Pendiente",
      inactive: "Inactivo",
      guardianDashboard: "Panel de Tutores",
      monitorLovedOnes: "Monitorea las actividades de tus seres queridos",
      notificationsOn: "Notificaciones Activadas",
      notificationsOff: "Notificaciones Desactivadas",
      connectedSeniors: "Adultos Mayores Conectados",
      lastSeen: "Visto por última vez",
      recentEnrollments: "Inscripciones Recientes",
      enrolledOn: "Inscrito el",
      upcoming: "Próximo",
      medicineAlerts: "Alertas de Medicamentos",
      scheduledFor: "Programado para",
      taken: "Tomado",
      quickActions: "Acciones Rápidas",
      viewAllActivities: "Ver Todas las Actividades",
      setCustomAlerts: "Configurar Alertas Personalizadas",
      error: "Error",
      fillAllFields: "Por favor completa todos los campos requeridos",
      medicineAdded: "Medicamento Agregado",
      addedSuccessfully: "ha sido agregado exitosamente",
      medicineTaken: "Medicamento Tomado",
      markedAsTaken: "Medicamento marcado como tomado",
      medicineSkipped: "Medicamento Omitido",
      reminderSkipped: "El recordatorio ha sido omitido",
      stayHealthy: "Mantente al día con tu salud",
      addMedicine: "Agregar Medicamento",
      addNewMedicine: "Agregar Nuevo Medicamento",
      medicineName: "Nombre del Medicamento",
      enterMedicineName: "Ingresa nombre del medicamento",
      dosage: "Dosis",
      enterDosage: "Ingresa dosis",
      frequency: "Frecuencia",
      selectFrequency: "Selecciona frecuencia",
      onceDaily: "Una vez al día",
      twiceDaily: "Dos veces al día",
      threeTimes: "Tres veces al día",
      weekly: "Semanal",
      time: "Hora",
      skip: "Omitir",
      viewYourEvents: "Ver tus eventos próximos e inscritos",
      confirmed: "Confirmado",
      cancelled: "Cancelado",
      viewDetails: "Ver Detalles",
    },
    hi: {
      appTitle: "वरिष्ठ देखभाल मंच",
      appSubtitle: "वरिष्ठों और अभिभावकों को जोड़ना",
      nearbyEvents: "निकटवर्ती कार्यक्रम",
      myEnrollments: "मेरे नामांकन",
      medicineReminders: "दवा रिमाइंडर",
      chatWithGuardian: "अभिभावक के साथ चैट",
      profile: "प्रोफ़ाइल",
      guardians: "अभिभावक",
      guardianPanel: "अभिभावक पैनल",
      seniorMode: "वरिष्ठ मोड",
      guardianMode: "अभिभावक मोड",
      upcomingEvents: "आगामी कार्यक्रम",
      medicinesScheduled: "निर्धारित दवाएं",
      connectedGuardians: "जुड़े अभिभावक",
      adminDashboard: "प्रशासक डैशबोर्ड",
      adminDashboardDesc: "उपयोगकर्ता, कार्यक्रम और सिस्टम सेटिंग्स का प्रबंधन करें",
      overview: "अवलोकन",
      userManagement: "उपयोगकर्ता प्रबंधन",
      eventManagement: "कार्यक्रम प्रबंधन",
      eventManagementDesc: "कार्यक्रम, कार्यक्रम और पंजीकरण का प्रबंधन करें",
      systemAlerts: "सिस्टम अलर्ट",
      systemSettings: "सिस्टम सेटिंग्स",
      systemSettingsDesc: "सिस्टम प्राथमिकताएं और सुरक्षा सेटिंग्स कॉन्फ़िगर करें",
      totalUsers: "कुल उपयोगकर्ता",
      activeSeniors: "सक्रिय वरिष्ठ",
      pendingAlerts: "लंबित अलर्ट",
      systemHealth: "सिस्टम स्वास्थ्य",
      recentUsers: "हाल के उपयोगकर्ता",
      recentAlerts: "हाल के अलर्ट",
      filter: "फ़िल्टर",
      export: "निर्यात",
      addUser: "उपयोगकर्ता जोड़ें",
      edit: "संपादित करें",
      view: "देखें",
      search: "खोजें",
      settings: "सेटिंग्स",
      name: "नाम",
      type: "प्रकार",
      status: "स्थिति",
      joinDate: "शामिल होने की तारीख",
      lastActivity: "अंतिम गतिविधि",
      actions: "कार्य",
      userProfile: "उपयोगकर्ता प्रोफाइल",
      manageYourInfo: "अपनी व्यक्तिगत जानकारी का प्रबंधन करें",
      editProfile: "प्रोफाइल संपादित करें",
      save: "सहेजें",
      yearsOld: "वर्ष की आयु",
      age: "आयु",
      address: "पता",
      emergencyContact: "आपातकालीन संपर्क",
      medicalConditions: "चिकित्सा स्थितियां",
      stayConnected: "अपने परिवार के साथ जुड़े रहें",
      refresh: "रीफ्रेश",
      messages: "संदेश",
      chatWith: "बात करें",
      typeYourMessage: "अपना संदेश टाइप करें",
      morningYoga: "सुबह योग सत्र",
      morningYogaDesc: "वरिष्ठों के लिए डिज़ाइन किए गए एक सौम्य योग सत्र में शामिल हों",
      healthCheckup: "स्वास्थ्य जांच शिविर",
      healthCheckupDesc: "डॉक्टरों के साथ मुफ्त स्वास्थ्य जांच और परामर्श",
      socialGathering: "सामुदायिक सामाजिक घंटा",
      socialGatheringDesc: "अन्य समुदायिक सदस्यों से मिलें और जुड़ें",
      enrollmentSuccess: "नामांकन सफल",
      enrolledIn: "आपका नामांकन हो गया है",
      filterEvents: "कार्यक्रम फ़िल्टर करें",
      healthWellness: "स्वास्थ्य और कल्याण",
      healthcare: "स्वास्थ्य सेवा",
      social: "सामाजिक",
      away: "दूर",
      enrolled: "नामांकित",
      enrollNow: "अभी नामांकन करें",
      guardianAdded: "अभिभावक जोड़ा गया",
      invitationSent: "निमंत्रण सफलतापूर्वक भेजा गया",
      guardianRemoved: "अभिभावक हटाया गया",
      connectionRemoved: "कनेक्शन सफलतापूर्वक हटाया गया",
      guardianConnections: "अभिभावक कनेक्शन",
      manageGuardians: "अपने अभिभावक कनेक्शन का प्रबंधन करें",
      addGuardian: "अभिभावक जोड़ें",
      addNewGuardian: "नया अभिभावक जोड़ें",
      fullName: "पूरा नाम",
      enterName: "पूरा नाम दर्ज करें",
      relation: "रिश्ता",
      enterRelation: "रिश्ता दर्ज करें",
      phoneNumber: "फोन नंबर",
      enterPhone: "फोन नंबर दर्ज करें",
      email: "ईमेल",
      optional: "वैकल्पिक",
      enterEmail: "ईमेल पता दर्ज करें",
      sendInvitation: "निमंत्रण भेजें",
      cancel: "रद्द करें",
      active: "सक्रिय",
      pending: "लंबित",
      inactive: "निष्क्रिय",
      guardianDashboard: "अभिभावक डैशबोर्ड",
      monitorLovedOnes: "अपने प्रियजनों की गतिविधियों की निगरानी करें",
      notificationsOn: "सूचनाएं चालू",
      notificationsOff: "सूचनाएं बंद",
      connectedSeniors: "जुड़े वरिष्ठ",
      lastSeen: "अंतिम बार देखा गया",
      recentEnrollments: "हाल के नामांकन",
      enrolledOn: "नामांकित",
      upcoming: "आगामी",
      medicineAlerts: "दवा अलर्ट",
      scheduledFor: "के लिए निर्धारित",
      taken: "लिया गया",
      quickActions: "त्वरित क्रियाएं",
      viewAllActivities: "सभी गतिविधियां देखें",
      setCustomAlerts: "कस्टम अलर्ट सेट करें",
      error: "त्रुटि",
      fillAllFields: "कृपया सभी आवश्यक फ़ील्ड भरें",
      medicineAdded: "दवा जोड़ी गई",
      addedSuccessfully: "सफलतापूर्वक जोड़ा गया",
      medicineTaken: "दवा ली गई",
      markedAsTaken: "दवा को लिया गया के रूप में चिह्नित किया गया",
      medicineSkipped: "दवा छोड़ी गई",
      reminderSkipped: "रिमाइंडर छोड़ा गया है",
      stayHealthy: "अपने स्वास्थ्य के शीर्ष पर रहें",
      addMedicine: "दवा जोड़ें",
      addNewMedicine: "नई दवा जोड़ें",
      medicineName: "दवा का नाम",
      enterMedicineName: "दवा का नाम दर्ज करें",
      dosage: "खुराक",
      enterDosage: "खुराक दर्ज करें",
      frequency: "आवृत्ति",
      selectFrequency: "आवृत्ति चुनें",
      onceDaily: "दिन में एक बार",
      twiceDaily: "दिन में दो बार",
      threeTimes: "दिन में तीन बार",
      weekly: "साप्ताहिक",
      time: "समय",
      skip: "छोड़ें",
      viewYourEvents: "अपने आगामी और नामांकित कार्यक्रम देखें",
      confirmed: "पुष्ट",
      cancelled: "रद्द",
      viewDetails: "विवरण देखें",
    },
    ne: {
      appTitle: "वरिष्ठ हेरचाह प्लेटफर्म",
      appSubtitle: "वरिष्ठहरू र अभिभावकहरूलाई जोड्दै",
      nearbyEvents: "नजिकका कार्यक्रमहरू",
      myEnrollments: "मेरा दर्ता",
      medicineReminders: "औषधि रिमाइन्डर",
      chatWithGuardian: "अभिभावकसँग कुराकानी",
      profile: "प्रोफाइल",
      guardians: "अभिभावकहरू",
      guardianPanel: "अभिभावक प्यानल",
      seniorMode: "वरिष्ठ मोड",
      guardianMode: "अभिभावक मोड",
      upcomingEvents: "आगामी कार्यक्रमहरू",
      medicinesScheduled: "निर्धारित औषधिहरू",
      connectedGuardians: "जडान भएका अभिभावकहरू",
      adminDashboard: "प्रशासक ड्यासबोर्ड",
      adminDashboardDesc: "प्रयोगकर्ता, कार्यक्रम र प्रणाली सेटिङहरू व्यवस्थापन गर्नुहोस्",
      overview: "अवलोकन",
      userManagement: "प्रयोगकर्ता व्यवस्थापन",
      eventManagement: "कार्यक्रम व्यवस्थापन",
      eventManagementDesc: "कार्यक्रम, तालिका र दर्ता व्यवस्थापन गर्नुहोस्",
      systemAlerts: "प्रणाली अलर्टहरू",
      systemSettings: "प्रणाली सेटिङहरू",
      systemSettingsDesc: "प्रणाली प्राथमिकता र सुरक्षा सेटिङहरू कन्फिगर गर्नुहोस्",
      totalUsers: "कुल प्रयोगकर्ताहरू",
      activeSeniors: "सक्रिय वरिष्ठहरू",
      pendingAlerts: "बाँकी अलर्टहरू",
      systemHealth: "प्रणाली स्वास्थ्य",
      recentUsers: "हालका प्रयोगकर्ताहरू",
      recentAlerts: "हालका अलर्टहरू",
      filter: "फिल्टर",
      export: "निर्यात",
      addUser: "प्रयोगकर्ता थप्नुहोस्",
      edit: "सम्पादन गर्नुहोस्",
      view: "हेर्नुहोस्",
      search: "खोज्नुहोस्",
      settings: "सेटिङहरू",
      name: "नाम",
      type: "प्रकार",
      status: "स्थिति",
      joinDate: "सामेल भएको मिति",
      lastActivity: "अन्तिम गतिविधि",
      actions: "कार्यहरू",
      userProfile: "प्रयोगकर्ता प्रोफाइल",
      manageYourInfo: "आफ्नो व्यक्तिगत जानकारी व्यवस्थापन गर्नुहोस्",
      editProfile: "प्रोफाइल सम्पादन गर्नुहोस्",
      save: "बचत गर्नुहोस्",
      yearsOld: "वर्षको",
      age: "उमेर",
      address: "ठेगाना",
      emergencyContact: "आपतकालीन सम्पर्क",
      medicalConditions: "चिकित्सा अवस्थाहरू",
      stayConnected: "आफ्नो परिवारसँग जोडिएर बस्नुहोस्",
      refresh: "रिफ्रेस गर्नुहोस्",
      messages: "सन्देशहरू",
      chatWith: "कुराकानी गर्नुहोस्",
      typeYourMessage: "आफ्नो सन्देश टाइप गर्नुहोस्",
      morningYoga: "बिहानको योग सत्र",
      morningYogaDesc: "वरिष्ठहरूका लागि डिजाइन गरिएको कोमल योग सत्रमा सामेल हुनुहोस्",
      healthCheckup: "स्वास्थ्य जाँच शिविर",
      healthCheckupDesc: "डाक्टरहरूसँग निःशुल्क स्वास्थ्य जाँच र परामर्श",
      socialGathering: "सामुदायिक सामाजिक घण्टा",
      socialGatheringDesc: "अन्य समुदायका सदस्यहरूसँग भेट्नुहोस् र जोडिनुहोस्",
      enrollmentSuccess: "दर्ता सफल",
      enrolledIn: "तपाईं दर्ता भएको छ",
      filterEvents: "कार्यक्रमहरू फिल्टर गर्नुहोस्",
      healthWellness: "स्वास्थ्य र कल्याण",
      healthcare: "स्वास्थ्य सेवा",
      social: "सामाजिक",
      away: "टाढा",
      enrolled: "दर्ता भएको",
      enrollNow: "अहिले दर्ता गर्नुहोस्",
      guardianAdded: "अभिभावक थपियो",
      invitationSent: "निमन्त्रणा सफलतापूर्वक पठाइयो",
      guardianRemoved: "अभिभावक हटाइयो",
      connectionRemoved: "जडान सफलतापूर्वक हटाइयो",
      guardianConnections: "अभिभावक जडानहरू",
      manageGuardians: "आफ्नो अभिभावक जडानहरू व्यवस्थापन गर्नुहोस्",
      addGuardian: "अभिभावक थप्नुहोस्",
      addNewGuardian: "नयाँ अभिभावक थप्नुहोस्",
      fullName: "पूरा नाम",
      enterName: "पूरा नाम प्रविष्ट गर्नुहोस्",
      relation: "सम्बन्ध",
      enterRelation: "सम्बन्ध प्रविष्ट गर्नुहोस्",
      phoneNumber: "फोन नम्बर",
      enterPhone: "फोन नम्बर प्रविष्ट गर्नुहोस्",
      email: "इमेल",
      optional: "वैकल्पिक",
      enterEmail: "इमेल ठेगाना प्रविष्ट गर्नुहोस्",
      sendInvitation: "निमन्त्रणा पठाउनुहोस्",
      cancel: "रद्द गर्नुहोस्",
      active: "सक्रिय",
      pending: "बाँकी",
      inactive: "निष्क्रिय",
      guardianDashboard: "अभिभावक ड्यासबोर्ड",
      monitorLovedOnes: "आफ्ना प्रियजनहरूको गतिविधिहरू निगरानी गर्नुहोस्",
      notificationsOn: "सूचनाहरू चालु",
      notificationsOff: "सूचनाहरू बन्द",
      connectedSeniors: "जडान भएका वरिष्ठहरू",
      lastSeen: "अन्तिम पटक देखियो",
      recentEnrollments: "हालका दर्ताहरू",
      enrolledOn: "दर्ता गरिएको",
      upcoming: "आगामी",
      medicineAlerts: "औषधि अलर्टहरू",
      scheduledFor: "लागि निर्धारित",
      taken: "लिइएको",
      quickActions: "छिटो कार्यहरू",
      viewAllActivities: "सबै गतिविधिहरू हेर्नुहोस्",
      setCustomAlerts: "कस्टम अलर्टहरू सेट गर्नुहोस्",
      error: "त्रुटि",
      fillAllFields: "कृपया सबै आवश्यक फिल्डहरू भर्नुहोस्",
      medicineAdded: "औषधि थपियो",
      addedSuccessfully: "सफलतापूर्वक थपियो",
      medicineTaken: "औषधि लिइयो",
      markedAsTaken: "औषधि लिइएको रूपमा चिन्ह लगाइयो",
      medicineSkipped: "औषधि छोडियो",
      reminderSkipped: "रिमाइन्डर छोडिएको छ",
      stayHealthy: "आफ्नो स्वास्थ्यको शीर्षमा रहनुहोस्",
      addMedicine: "औषधि थप्नुहोस्",
      addNewMedicine: "नयाँ औषधि थप्नुहोस्",
      medicineName: "औषधिको नाम",
      enterMedicineName: "औषधिको नाम प्रविष्ट गर्नुहोस्",
      dosage: "खुराक",
      enterDosage: "खुराक प्रविष्ट गर्नुहोस्",
      frequency: "आवृत्ति",
      selectFrequency: "आवृत्ति चयन गर्नुहोस्",
      onceDaily: "दिनमा एक पटक",
      twiceDaily: "दिनमा दुई पटक",
      threeTimes: "दिनमा तीन पटक",
      weekly: "साप्ताहिक",
      time: "समय",
      skip: "छोड्नुहोस्",
      viewYourEvents: "आफ्ना आगामी र दर्ता गरिएका कार्यक्रमहरू हेर्नुहोस्",
      confirmed: "पुष्टि भएको",
      cancelled: "रद्द गरिएको",
      viewDetails: "विवरणहरू हेर्नुहोस्",
    }
  };

  const t = (key: TranslationKey): string => {
    return translations[language][key] || key;
  };

  return {
    language,
    setLanguage,
    t,
  };
};
