// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paruhccadbglvbqwqxvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcnVoY2NhZGJnbHZicXdxeHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTUzNjIsImV4cCI6MjA2Nzk5MTM2Mn0.0gpKlo7L5ZAacL6fqlMmyaTZehJ1EEw394LRA30FHBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});